version: "3.8"
services:
  app:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8088
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8088:8088
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - ALGORITHM=${ALGORITHM}
      - MODE=${MODE}
    depends_on:
      - db
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: on-failure
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/myrealm.json
    ports:
      - 8080:8080

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
    ports:
      - 127.0.0.1:16543:5432
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data:
